### ISSUE TITLE
changing mouse mode to relative mode with extension guacamole-auth-noauth-0.9.14

### ISSUE THREAD

**Issue by codekoch** [cloudshare/guacamole-client#1]
I use the extension guacamole-auth-noauth-0.9.14.jar on a raspberry pi and its working well connected to an ipad. But i miss the possibility to switch the mouse mode to use the pencil of the ipad.
Can anyone tell me how to change the mouse emulation to relative mode?
The web interface is not showing any settings or something else...just the screen of the pi.

Thanks

**Comment by jonathancloudshare** [comment]
Hi @codekoch, this repo is a fork of https://github.com/apache/guacamole-client for CloudShare (www.cloudshare.com) purposes. 

Check out the original repo, in their README they say you can report issues here: https://issues.apache.org/jira/browse/GUACAMOLE/

I'm going to close this and maybe close the Issues tab as well.

Good luck!
